#ifndef _WEBPAGE_H
#define _WEBPAGE_H
#include <Arduino.h>
const char* webPage = 
"<!DOCTYPE html>\n"
"<html>\n"
"\n"
"<head>\n"
"    <title>TTGO Recovery</title>\n"
"    <style>\n"
"        *,\n"
"        *:before,\n"
"        *:after {\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 100vh;\n"
"            background-color: #333;\n"
"            color: #fff;\n"
"        }\n"
"\n"
"        #settings {\n"
"            background-color: #444;\n"
"            padding: 30px;\n"
"            border-radius: 8px;\n"
"            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"        }\n"
"\n"
"        label {\n"
"            font-weight: bold;\n"
"            font-size: 1.2em;\n"
"        }\n"
"\n"
"        input,\n"
"        select {\n"
"            width: 100%;\n"
"            padding: 15px;\n"
"            margin: 10px 0 20px;\n"
"            border-radius: 4px;\n"
"            border: 1px solid #ccc;\n"
"            font-size: 1.1em;\n"
"            color: #fff;\n"
"            background-color: #555;\n"
"        }\n"
"\n"
"        button {\n"
"            background-color: #4CAF50;\n"
"            color: white;\n"
"            padding: 15px;\n"
"            margin: 10px 0;\n"
"            border: none;\n"
"            cursor: pointer;\n"
"            font-size: 1.1em;\n"
"            border-radius: 4px;\n"
"        }\n"
"\n"
"        button:hover {\n"
"            background-color: #45a049;\n"
"        }\n"
"\n"
"        @media (max-width: 600px) {\n"
"            #settings {\n"
"                width: 100%;\n"
"                font-size: 2em;\n"
"            }\n"
"        }\n"
"    </style>\n"
"    <script>\n"
"        function createOptions(id, options) {\n"
"            var select = document.getElementById(id);\n"
"            for (var i = 0; i < options.length; i++) {\n"
"                var option = document.createElement('option');\n"
"                option.value = options[i];\n"
"                option.text = options[i];\n"
"                select.appendChild(option);\n"
"            }\n"
"        }\n"
"\n"
"        function sendPostRequest(url, value) {\n"
"            // Use the fetch function to send a POST request\n"
"            fetch(url, {\n"
"                method: 'POST',\n"
"                headers: {\n"
"                    'Content-Type': 'text/htnml charset=UTF-8',\n"
"                },\n"
"                body: value\n"
"            });\n"
"        }\n"
"        window.onload = function () {\n"
"\n"
"            var spreadingFactors = [6, 7, 8, 9, 10, 11, 12]; // Replace with your actual spreading factors\n"
"            var bandwidths = [10, 15, 20, 31, 41, 62, 125, 250, 500]; // Replace with your actual bandwidths\n"
"            var codingRates = ['4/5', '4/6', '4/7', '4/8']; // Replace with your actual coding rates\n"
"\n"
"            createOptions('spreadingFactor', spreadingFactors);\n"
"            createOptions('bandwidth', bandwidths);\n"
"            createOptions('codingRate', codingRates);\n"
"\n"
"            var button = document.getElementById('submit-btn');\n"
"\n"
"            // Fetch the initial values\n"
"            Promise.all([\n"
"                fetch('/frequency').then(response => response.text()).then(value => document.getElementById('frequency').value = value),\n"
"                fetch('/spreadingFactor').then(response => response.text()).then(value => document.getElementById('spreadingFactor').value = value),\n"
"                fetch('/bandwidth').then(response => response.text()).then(value => document.getElementById('bandwidth').value = value),\n"
"                fetch('/codingRate').then(response => response.text()).then(value => document.getElementById('codingRate').value = value),\n"
"            ]).catch(error => console.error('Error:', error));\n"
"\n"
"            // Add an event listener for the click event\n"
"            button.addEventListener('click', function (event) {\n"
"                // Prevent the button from submitting a form\n"
"                event.preventDefault();\n"
"                // Send a POST request for each input field\n"
"                Promise.all([\n"
"                    sendPostRequest('/frequency', document.getElementById('frequency').value),\n"
"                    sendPostRequest('/spreadingFactor', document.getElementById('spreadingFactor').value),\n"
"                    sendPostRequest('/bandwidth', document.getElementById('bandwidth').value),\n"
"                    sendPostRequest('/codingRate', document.getElementById('codingRate').value)\n"
"                ]).then(function () {\n"
"                    // All fetch requests have completed\n"
"                    // You can now do something else\n"
"                });\n"
"            });\n"
"        };\n"
"    </script>\n"
"</head>\n"
"\n"
"<body>\n"
"    <div id=\"settings\">\n"
"        <h1>RTU HPR Recovery</h1> <!-- Add this line to insert a title -->\n"
"        <label for=\"frequency\">Frequency:</label><br>\n"
"        <input type=\"number\" id=\"frequency\" name=\"frequency\" step=\"0.001\" value=\"433.000\"><br>\n"
"        <label for=\"spreadingFactor\">Spreading Factor:</label><br>\n"
"        <select id=\"spreadingFactor\" name=\"spreadingFactor\"></select><br>\n"
"        <label for=\"bandwidth\">Bandwidth:</label><br>\n"
"        <select id=\"bandwidth\" name=\"bandwidth\"></select><br>\n"
"        <label for=\"codingRate\">Coding Rate:</label><br>\n"
"        <select id=\"codingRate\" name=\"codingRate\"></select><br>\n"
"        <button id=\"submit-btn\">Apply Settings</button>\n"
"    </div>\n"
"</body>\n"
"\n"
"</html>\n";
#endif // _WEBPAGE_H
